# Generated by Django 5.1.14 on 2025-11-13 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gaveta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='Número físico da gaveta (ex: 1, 2, 3...)', unique=True)),
                ('nome', models.CharField(blank=True, help_text='Nome amigável (ex: Chaves, Alicates, Soquetes)', max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True, help_text='Se desmarcado, a gaveta não é usada pelo sistema')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gaveta',
                'verbose_name_plural': 'Gavetas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, help_text='Código interno / patrimonial (opcional)', max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('posicao', models.PositiveSmallIntegerField(help_text='Posição/slot na gaveta (linkado com o índice de ROI da visão)')),
                ('quantidade', models.PositiveIntegerField(default=1, help_text='Quantidade dessa ferramenta (se houver mais de uma igual)')),
                ('ativa', models.BooleanField(default=True, help_text='Se desmarcado, não aparece como disponível para retirada')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('gaveta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ferramentas', to='inventario.gaveta')),
            ],
            options={
                'verbose_name': 'Ferramenta',
                'verbose_name_plural': 'Ferramentas',
                'ordering': ['gaveta', 'posicao', 'nome'],
                'unique_together': {('gaveta', 'posicao')},
            },
        ),
    ]
