# Generated by Django 5.1.14 on 2025-11-13 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(help_text='Código interno / matrícula do colaborador', max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CartaoNFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='UID lido pelo RC522 (enviado via MQTT pela Rock Pi)', max_length=32, unique=True, verbose_name='UID do cartão')),
                ('apelido', models.CharField(blank=True, help_text="Opcional: apelido do cartão (ex: 'Capacete', 'Cartão reserva')", max_length=50)),
                ('ativo', models.BooleanField(default=True, help_text='Se desmarcado, o cartão não autoriza uso da caixa')),
                ('ultimo_uso_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='usuarios.colaborador')),
            ],
            options={
                'verbose_name': 'Cartão NFC',
                'verbose_name_plural': 'Cartões NFC',
            },
        ),
    ]
