# Generated by Django 5.1.14 on 2025-11-13 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Em andamento'), ('F', 'Finalizada'), ('C', 'Cancelada'), ('E', 'Expirada / Timeout')], default='A', max_length=1)),
                ('payload_inicial', models.JSONField(blank=True, null=True)),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes', to='usuarios.cartaonfc')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='usuarios.colaborador')),
            ],
            options={
                'verbose_name': 'Sessão de Uso',
                'verbose_name_plural': 'Sessões de Uso',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoFerramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('R', 'Retirada'), ('D', 'Devolução')], max_length=1)),
                ('gaveta_numero', models.PositiveSmallIntegerField(help_text='Número da gaveta no momento da operação')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('imagem_path', models.CharField(blank=True, help_text='Caminho relativo da imagem capturada (se houver)', max_length=255)),
                ('confirmado_visao', models.BooleanField(default=False, help_text='Se True, a visão computacional confirmou a movimentação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='inventario.ferramenta')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='operacoes.sessaouso')),
            ],
            options={
                'verbose_name': 'Movimentação de Ferramenta',
                'verbose_name_plural': 'Movimentações de Ferramenta',
            },
        ),
    ]
